name: Question
description: Ask a question about usage or troubleshooting
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        **Tip:** Check the README troubleshooting section first.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant context (what you've tried, your setup, etc.)

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Installation / Setup
        - Usage / Commands
        - Customization
        - Troubleshooting
        - Contributing
        - Other
    validations:
      required: true
